on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: p1xelelse/image_for_cpp
    steps:
      - uses: actions/checkout@v2 
      - run: make check
  build:
    runs-on: ubuntu-latest
    container: p1xelelse/image_for_cpp
    needs: [check]
    steps:
    - uses: actions/checkout@v2 
    - run: make build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: build
  test:
    runs-on: ubuntu-latest
    container: p1xelelse/image_for_cpp
    needs: [build]
    steps:
      - uses: actions/checkout@v2 
      - run: make test
  memtest:
    runs-on: ubuntu-latest
    container: p1xelelse/image_for_cpp
    needs: [build]
    steps:
      - uses: actions/checkout@v2 
      - run: make memtest
      - name: Upload valgrind artifacts
        uses: actions/upload-artifact@v2
        with:
          path: valgrind.log
      - name: Upload code coverage artifacts
        uses: actions/upload-artifact@v23
        with:
          path: build/report/vector_array


